server:
  port: 8080
spring:
  application:
    name: SampleSpringBootApplication2
test:
  value: default
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
---
spring:
  profiles: prod
test:
  value: pro